Import('memcachedEnv')
Import('mainEnv')

myEnv = memcachedEnv.Clone() 

if myEnv['BUILD_PVAR'] == True:

	if mainEnv['BUILD_LINKAGE'] == 'dynamic':
		pvarLibrary = myEnv.SharedLibrary('pvar', 'pvar.c')
	else:
		pvarLibrary = myEnv.StaticLibrary('pvar', 'pvar.c')

	Return('pvarLibrary')
else:
	sources = Split("""
			   assoc.c
			   helper.c
			   items.c
			   memcached.c
		   	   slabs.c
			   stats.c
			   thread.c
                	   """)

	Import('pvarLibrary')
	myEnv.Append(LIBS = [pvarLibrary])

	if mainEnv['STATIC_LINK'] == False :
		myEnv.Append(LIBS = ['event'])
		
	else:
		myEnv.Append(LIBS = [File('/usr/lib/x86_64-linux-gnu/libevent.a')])

	myEnv.Program('memcached', sources)
