Import('examplesEnv')
Import('mainEnv')

myEnv = examplesEnv.Clone()


if myEnv['BUILD_PVAR'] == True:

	if mainEnv['BUILD_LINKAGE'] == 'dynamic':
		pvarLibrary = myEnv.SharedLibrary('pvar', 'pvar.c')
	else:
		pvarLibrary = myEnv.StaticLibrary('pvar', 'pvar.c')

	Return('pvarLibrary')
else:
	sources = Split("""main.c""")
	myEnv.Program('simple', sources)
